version: '3.8'

services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        privileged: true
        shm_size: 8g
    app:
        build: .
        restart:
            on-failure
        depends_on:
            - chrome




